### ISSUE TITLE
"Server response to hostname packet is error 0x08" error in one computer and not another

### ISSUE THREAD

**Issue by pablob127** [utknoxville/openconnect-pulse-gui#22]
I recently installed openconnect-pulse-gui in a new computer, and when I try to connect, I get the following error (with some context):

`<Popen: returncode: None args: ['openconnect', '--protocol', 'nc', '-C', 'DS...>
Connected to xxx.yyy.zzz.aaa:443
SSL negotiation with vpn.domain
Connected to HTTPS on vpn.domain with ciphersuite (TLS1.2)-(RSA)-(AES-256-CBC)-(SHA256)
Server response to hostname packet is error 0x08
This seems to indicate that the server has disabled support for
Juniper's older oNCP protocol, and only allows connections using
the newer Junos Pulse protocol. This version of OpenConnect has
EXPERIMENTAL support for Pulse using --prot=pulse
Creating SSL connection failed
Unknown error; exiting.
`

If I try to change the protocol to "pulse", it does not work (which is what the docs imply anyway).

What makes this strange, is that in another (older) computer, with the same versions of all software, the connection gets successfully established.

Both computers are running Debian 12 (bookworm), with openconnect 9.01-3 and the exact same version of openconnect-pulse-gui.

Since one computer can connect (using the same authentication info), it cannot be the server has been globally configured to to reject the old protocol, there must be something different between the two computers that leads to this. But I have no idea how to find that.
Any suggestions? I'd really need to solve this.

Thanks!

**Comment by kbirkela** [comment]
That is interesting that it works on one but not the other. I'm curious if you copied the `~/.config/pulse-gui-cookie` file from your working box the the non-working box if the behavior changes.

**Comment by pablob127** [comment]
> That is interesting that it works on one but not the other. I'm curious if you copied the `~/.config/pulse-gui-cookie` file from your working box the the non-working box if the behavior changes.

I did not find that file in either computer, things seem to be getting weird! Could it be somewhere else?

**Comment by pablob127** [comment]
Never mind, it looks like I was not using the same URL in both computers. User problem! :-)
